# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nolib_nbdev',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/nolib_nbdev',
                'lib_path': 'nolib_nbdev'},
  'syms': {'nolib_nbdev.core': {'nolib_nbdev.core.foo': ('core.html#foo', 'nolib_nbdev/core.py')}}}